# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

      - name: Compress build to ZIP file
        run: |
            cd build
            pwd
            touch Procfile
            echo web: npx serve >> Procfile #to run the applications once the build deployed successfully
            zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.KEY }}
            aws-secret-access-key: ${{ secrets.VALUE }}
            aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy ZIP file to S3 bucket
        run: |
            cd build
            pwd
            aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.AWS_BUCKET_NAME }}
      - name: Completion of CI Pipleline
        run: echo "Build finished successfully"
